### ISSUE TITLE
Support Dynamic Style transformation

### ISSUE THREAD

**Issue by SteveTownsend** [SteveTownsend/AllGUDMeshGen#11]
Never used it, there is interest at Discord. Can it be done in patcher?

**Comment by shoegorath** [comment]
its only used for animated weapons and there arent many. in my massive mod list, the only mods that used dynamic were wheels of lull, relics of hyrule, and LOTD (since it displays all those weapons and creates replcas) i attached the log from those mods run with dynamic the (4 failed just didnt exist)
[Log.txt](https://github.com/SteveTownsend/AllGUDMeshGen/files/6438503/Log.txt)

**Comment by SteveTownsend** [comment]
thanks - do you have to run the script twice, once for static and once for
dynamic? I would hope to combine that all in one pass

**Comment by shoegorath** [comment]
From my understanding of it, you run the static, and it tells you which weapons contain dynamic displays. Ignore crossbows and rifles. Then run the dynamic on just those. Then run the alternate mesh scripts, then the fixes alternate mesh scripts. Then you run the first script again on everything, (since new meshes were created). Then the skeleton patcher script and then the item positioner last. And then there's some scripts that you download and place overwriting xpmse to prevent weapon flicker while equipped on the body

**Comment by SteveTownsend** [comment]
I am leaving this scripted. Seems virtually unused, and too much work and risk.
